services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      APP_ENV: development
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
